# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(271, 527)
        self.btnInsertSubject = QtWidgets.QPushButton(Form)
        self.btnInsertSubject.setGeometry(QtCore.QRect(10, 430, 251, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnInsertSubject.setFont(font)
        self.btnInsertSubject.setObjectName("btnInsertSubject")
        self.inputGroup = QtWidgets.QLineEdit(Form)
        self.inputGroup.setGeometry(QtCore.QRect(10, 80, 251, 31))
        self.inputGroup.setObjectName("inputGroup")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label.setObjectName("label")
        self.inputSubjectName = QtWidgets.QLineEdit(Form)
        self.inputSubjectName.setGeometry(QtCore.QRect(10, 140, 251, 31))
        self.inputSubjectName.setObjectName("inputSubjectName")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 91, 21))
        self.label_2.setObjectName("label_2")
        self.inputDay = QtWidgets.QLineEdit(Form)
        self.inputDay.setGeometry(QtCore.QRect(10, 200, 251, 31))
        self.inputDay.setObjectName("inputDay")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 101, 21))
        self.label_3.setObjectName("label_3")
        self.inputPeriodFrom = QtWidgets.QLineEdit(Form)
        self.inputPeriodFrom.setGeometry(QtCore.QRect(10, 260, 251, 31))
        self.inputPeriodFrom.setObjectName("inputPeriodFrom")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 121, 21))
        self.label_4.setObjectName("label_4")
        self.inputPeriodTo = QtWidgets.QLineEdit(Form)
        self.inputPeriodTo.setGeometry(QtCore.QRect(10, 320, 251, 31))
        self.inputPeriodTo.setObjectName("inputPeriodTo")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 300, 101, 21))
        self.label_5.setObjectName("label_5")
        self.inputLecturer = QtWidgets.QLineEdit(Form)
        self.inputLecturer.setGeometry(QtCore.QRect(10, 380, 251, 31))
        self.inputLecturer.setObjectName("inputLecturer")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 360, 47, 21))
        self.label_6.setObjectName("label_6")
        self.btnPrintSchedules = QtWidgets.QPushButton(Form)
        self.btnPrintSchedules.setGeometry(QtCore.QRect(10, 480, 251, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnPrintSchedules.setFont(font)
        self.btnPrintSchedules.setObjectName("btnPrintSchedules")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(6, 9, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnInsertSubject.setText(_translate("Form", "INSERT SUBJECT"))
        self.label.setText(_translate("Form", "Group (ex: 1, 2, ..."))
        self.label_2.setText(_translate("Form", "Subject Name"))
        self.label_3.setText(_translate("Form", "Day (ex: 2, 3, ...)"))
        self.label_4.setText(_translate("Form", "Period from (ex: 1, ...)"))
        self.label_5.setText(_translate("Form", "Period to (ex: 4, ...)"))
        self.label_6.setText(_translate("Form", "Lecturer"))
        self.btnPrintSchedules.setText(_translate("Form", "PRINT SCHEDULES"))
        self.label_7.setText(_translate("Form", "DANG KY TIN CHI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
